name: Trigger Renovate Run

on:
  push:
    branches:
      - 'main'
  issues:
    types:
      - edited

jobs:
  renovate:
    name: Trigger Renovate Run
    runs-on: ubuntu-latest
    steps:
      - name: Split
        uses: winterjung/split@v2
        id: split
        with:
          separator: '/'
          msg: '${{ github.repository }}'
      - name: Trigger Renovate Run
        uses: actions/github-script@v8
        id: repositories
        with:
          github-token: ${{ secrets.RENOVATE_WORKFLOW_DISPATCH_TOKEN }}
          script: |
            await octokit.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: '${{ github.repository_owner }}',
              repo: 'renovate-runner',
              workflow_id: 'renovate.yaml',
              ref: 'main',
              inputs: {
                repo: '${{ steps.split.outputs._1 }}',
              },
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
